#!/usr/bin/env python3
"""
Puzzle Converter for Game Boy Crossword

Converts JSON puzzle definitions to C source files for inclusion in the ROM.

JSON Format:
{
    "title": "Puzzle Name",
    "grid": [
        "RADIAL#####WORDS",
        ".#.#.#####.#.#.#",
        ...
    ],
    "across": [
        {"number": 1, "clue": "Poorly made dial exploded (6)"},
        ...
    ],
    "down": [
        {"number": 1, "clue": "Crazy person in the attic (3)"},
        ...
    ]
}

Grid format:
- Capital letters A-Z: solution letter
- '#' or 'B': black/blocked cell
- '.': empty cell (no solution provided, for testing)
"""

import json
import sys
import os
from pathlib import Path

GRID_WIDTH = 15
GRID_HEIGHT = 15

def escape_string(s):
    """Escape a string for C source code."""
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')

def convert_puzzle(json_data, puzzle_index):
    """Convert a JSON puzzle to C source code."""
    title = json_data.get("title", f"Puzzle {puzzle_index + 1}")
    grid = json_data.get("grid", [])
    across_clues = json_data.get("across", [])
    down_clues = json_data.get("down", [])

    # Validate grid size
    if len(grid) != GRID_HEIGHT:
        print(f"Warning: Grid has {len(grid)} rows, expected {GRID_HEIGHT}")

    output = []
    output.append(f"// Puzzle {puzzle_index}: {title}")
    output.append(f"// Auto-generated by puzzle_converter.py")
    output.append("")

    # Generate clue strings
    output.append("// Across clues")
    for clue in across_clues:
        num = clue["number"]
        text = escape_string(clue["clue"])
        output.append(f'static const char puzzle{puzzle_index}_clue_{num}a[] = "{text}";')

    output.append("")
    output.append("// Down clues")
    for clue in down_clues:
        num = clue["number"]
        text = escape_string(clue["clue"])
        output.append(f'static const char puzzle{puzzle_index}_clue_{num}d[] = "{text}";')

    output.append("")

    # Generate clue arrays
    output.append("// Across clue array")
    output.append(f"static const Clue puzzle{puzzle_index}_across_clues[] = {{")
    for clue in across_clues:
        num = clue["number"]
        # Find position in grid
        start_x, start_y, length = find_word_position(grid, num, "across")
        output.append(f"    {{ {num}, {start_x}, {start_y}, {length}, puzzle{puzzle_index}_clue_{num}a }},")
    output.append("};")
    output.append("")

    output.append("// Down clue array")
    output.append(f"static const Clue puzzle{puzzle_index}_down_clues[] = {{")
    for clue in down_clues:
        num = clue["number"]
        start_x, start_y, length = find_word_position(grid, num, "down")
        output.append(f"    {{ {num}, {start_x}, {start_y}, {length}, puzzle{puzzle_index}_clue_{num}d }},")
    output.append("};")
    output.append("")

    # Generate grid template
    output.append("// Grid template")
    output.append(f"static const char puzzle{puzzle_index}_grid_template[GRID_HEIGHT][GRID_WIDTH + 1] = {{")
    for row in grid:
        # Normalize: convert '#' to 'B', pad/truncate to GRID_WIDTH
        normalized = row.replace('#', 'B')
        if len(normalized) < GRID_WIDTH:
            normalized += 'B' * (GRID_WIDTH - len(normalized))
        elif len(normalized) > GRID_WIDTH:
            normalized = normalized[:GRID_WIDTH]
        output.append(f'    "{normalized}",')
    output.append("};")
    output.append("")

    # Generate puzzle struct
    output.append(f"// Puzzle {puzzle_index} definition")
    output.append(f"static Puzzle puzzle{puzzle_index} = {{")
    output.append(f'    .title = "{escape_string(title)}",')
    output.append(f"    .across_count = {len(across_clues)},")
    output.append(f"    .down_count = {len(down_clues)},")
    output.append(f"    .across_clues = puzzle{puzzle_index}_across_clues,")
    output.append(f"    .down_clues = puzzle{puzzle_index}_down_clues,")
    output.append("};")

    return "\n".join(output)

def number_grid_cells(grid):
    """
    Number grid cells according to crossword conventions.
    Returns a dict mapping (x, y) -> clue_number for cells that start words,
    and sets of (clue_number, direction) for tracking.
    """
    cell_numbers = {}  # (x, y) -> clue_number
    across_starts = {}  # clue_number -> (x, y)
    down_starts = {}    # clue_number -> (x, y)
    current_num = 1

    def is_letter(x, y):
        if y < 0 or y >= len(grid) or x < 0 or x >= len(grid[y]):
            return False
        c = grid[y][x]
        return c not in ('#', 'B', '.') and c.isalpha()

    def is_black(x, y):
        if y < 0 or y >= len(grid) or x < 0 or x >= len(grid[y]):
            return True  # Out of bounds treated as black
        return grid[y][x] in ('#', 'B')

    for y in range(len(grid)):
        for x in range(len(grid[y]) if y < len(grid) else 0):
            if is_black(x, y):
                continue

            # Check if this cell starts an across word
            is_across_start = (is_black(x - 1, y) and is_letter(x + 1, y))

            # Check if this cell starts a down word
            is_down_start = (is_black(x, y - 1) and is_letter(x, y + 1))

            if is_across_start or is_down_start:
                cell_numbers[(x, y)] = current_num
                if is_across_start:
                    across_starts[current_num] = (x, y)
                if is_down_start:
                    down_starts[current_num] = (x, y)
                current_num += 1

    return cell_numbers, across_starts, down_starts


def find_word_position(grid, clue_num, direction):
    """Find the starting position and length of a word in the grid."""
    cell_numbers, across_starts, down_starts = number_grid_cells(grid)

    if direction == "across":
        if clue_num not in across_starts:
            print(f"Warning: Across clue {clue_num} not found in grid")
            return (0, 0, 1)
        start_x, start_y = across_starts[clue_num]
        # Count length
        length = 0
        x = start_x
        while x < len(grid[start_y]) and grid[start_y][x] not in ('#', 'B'):
            length += 1
            x += 1
        return (start_x, start_y, length)
    else:  # down
        if clue_num not in down_starts:
            print(f"Warning: Down clue {clue_num} not found in grid")
            return (0, 0, 1)
        start_x, start_y = down_starts[clue_num]
        # Count length
        length = 0
        y = start_y
        while y < len(grid) and start_x < len(grid[y]) and grid[y][start_x] not in ('#', 'B'):
            length += 1
            y += 1
        return (start_x, start_y, length)

def main():
    if len(sys.argv) < 2:
        print("Usage: puzzle_converter.py <puzzle.json> [output.c]")
        print("")
        print("Converts a JSON puzzle definition to C source code.")
        sys.exit(1)

    input_path = Path(sys.argv[1])
    if len(sys.argv) > 2:
        output_path = Path(sys.argv[2])
    else:
        output_path = input_path.with_suffix('.c')

    with open(input_path, 'r') as f:
        puzzle_data = json.load(f)

    c_code = convert_puzzle(puzzle_data, 0)

    with open(output_path, 'w') as f:
        f.write(c_code)

    print(f"Generated {output_path}")

if __name__ == "__main__":
    main()
