#include <string.h>
#include "puzzles.h"

// Sample cryptic crossword clues
static const char clue_1a[] = "Poorly made dial exploded";
static const char clue_4a[] = "Second letter from Greece";
static const char clue_7a[] = "Greeting from aloha waii";

static const char clue_1d[] = "Crazy person in the attic";
static const char clue_2d[] = "Worker insect at picnic";
static const char clue_3d[] = "Writing tool for authors";

// Sample clue arrays
static const Clue sample_across_clues[] = {
    { 1, 0, 0, 5, clue_1a },
    { 4, 0, 2, 4, clue_4a },
    { 7, 0, 4, 5, clue_7a },
};

static const Clue sample_down_clues[] = {
    { 1, 0, 0, 5, clue_1d },
    { 2, 2, 0, 5, clue_2d },
    { 3, 4, 0, 5, clue_3d },
};

// Sample 15x15 grid template
// # = black cell, . = empty white cell, A-Z = solution letters
// This is a simplified demo grid - real crosswords have symmetric patterns
static const char sample_grid_template[GRID_HEIGHT][GRID_WIDTH + 1] = {
    "RADIAL####WORDS",
    ".#.#.#####.#.#.",
    "BETA######ANT##",
    ".#.#######.#.##",
    "ALOHA######PEN#",
    "###############",
    "...............",
    "#.#.#.#.#.#.#.#",
    "...............",
    "###############",
    "...............",
    "#.#.#.#.#.#.#.#",
    "...............",
    "###############",
    "...............",
};
// Puzzle 0: March Cryptic
// Auto-generated by puzzle_converter.py

// Across clues
static const char puzzle0_clue_1a[] = "I enter football club in warlike mood, start off pretending (10)";
static const char puzzle0_clue_6a[] = "Discuss a hundred-odd hearts (4)";
static const char puzzle0_clue_9a[] = "Prominent trade worker (9)";
static const char puzzle0_clue_10a[] = "Gloomy nut freaks out on lithium (5)";
static const char puzzle0_clue_11a[] = "Older person lasts to samba step (3)";
static const char puzzle0_clue_13a[] = "How I'd thought to contain scope (5)";
static const char puzzle0_clue_14a[] = "Stop employ after assistant (5)";
static const char puzzle0_clue_15a[] = "Average German follows standard way of working (4)";
static const char puzzle0_clue_16a[] = "Grand artist read out work written by fan, a type of novel (7)";
static const char puzzle0_clue_18a[] = "Jolly about mega order being withdrawn by portable console (4, 3)";
static const char puzzle0_clue_19a[] = "The Spanish back an inclination (4)";
static const char puzzle0_clue_23a[] = "Rifle through morning rooms endlessly for bitter thing to swallow (5)";
static const char puzzle0_clue_24a[] = "Kazakh mercenary smuggles Cambodian (5)";
static const char puzzle0_clue_25a[] = "Age of queen, at first (3)";
static const char puzzle0_clue_27a[] = "Mistakenly take short run of wins (3,6)";
static const char puzzle0_clue_30a[] = "Palm off a ted (4)";
static const char puzzle0_clue_31a[] = "A scaly pope bastardised Revelations (10)";
static const char puzzle0_clue_36a[] = "Saffron I parcel out, special price not holding (5)";

// Down clues
static const char puzzle0_clue_1d[] = "Writer of fantastical movies gave note for lead actor (6)";
static const char puzzle0_clue_2d[] = "Pat back and forth? (3)";
static const char puzzle0_clue_3d[] = "Odds of flier making tree (3)";
static const char puzzle0_clue_4d[] = "Monet about to exclaim \"God!\" (6)";
static const char puzzle0_clue_5d[] = "Blows air on the Batman (8)";
static const char puzzle0_clue_7d[] = "See things are messed up, I launch late (11)";
static const char puzzle0_clue_8d[] = "Donations to church - model it health economics style, to begin with (6)";
static const char puzzle0_clue_10d[] = "Disliked posh juice pulp on a second try (9)";
static const char puzzle0_clue_12d[] = "In favour of resigned type loudly going after new advocate for children (11)";
static const char puzzle0_clue_13d[] = "Loud clothes, for what reason? (9)";
static const char puzzle0_clue_17d[] = "Daunt logs what bunnies do (8)";
static const char puzzle0_clue_20d[] = "Back when speaking meant no action taken (6)";
static const char puzzle0_clue_21d[] = "Makes you sick? Even celiac takes force (6)";
static const char puzzle0_clue_22d[] = "Irritate leg joint post-run (6)";
static const char puzzle0_clue_28d[] = "Before I enter the timeline (3)";
static const char puzzle0_clue_29d[] = "Record without second psychic power (3)";

// Across clue array
static const Clue puzzle0_across_clues[] = {
    { 1, 0, 0, 10, puzzle0_clue_1a },
    { 6, 11, 0, 4, puzzle0_clue_6a },
    { 9, 0, 2, 9, puzzle0_clue_9a },
    { 10, 10, 2, 5, puzzle0_clue_10a },
    { 11, 0, 4, 3, puzzle0_clue_11a },
    { 13, 4, 4, 5, puzzle0_clue_13a },
    { 14, 10, 4, 5, puzzle0_clue_14a },
    { 15, 1, 6, 4, puzzle0_clue_15a },
    { 16, 7, 6, 7, puzzle0_clue_16a },
    { 18, 1, 8, 7, puzzle0_clue_18a },
    { 19, 10, 8, 4, puzzle0_clue_19a },
    { 23, 0, 10, 5, puzzle0_clue_23a },
    { 24, 6, 10, 5, puzzle0_clue_24a },
    { 25, 12, 10, 3, puzzle0_clue_25a },
    { 27, 6, 12, 9, puzzle0_clue_27a },
    { 30, 0, 14, 4, puzzle0_clue_30a },
    { 31, 5, 14, 10, puzzle0_clue_31a },
    { 36, 0, 0, 1, puzzle0_clue_36a },
};

// Down clue array
static const Clue puzzle0_down_clues[] = {
    { 1, 0, 0, 6, puzzle0_clue_1d },
    { 2, 2, 0, 3, puzzle0_clue_2d },
    { 3, 4, 0, 3, puzzle0_clue_3d },
    { 4, 6, 0, 6, puzzle0_clue_4d },
    { 5, 8, 0, 8, puzzle0_clue_5d },
    { 7, 12, 0, 11, puzzle0_clue_7d },
    { 8, 14, 0, 6, puzzle0_clue_8d },
    { 10, 10, 2, 9, puzzle0_clue_10d },
    { 12, 2, 4, 11, puzzle0_clue_12d },
    { 13, 4, 4, 9, puzzle0_clue_13d },
    { 17, 0, 0, 1, puzzle0_clue_17d },
    { 20, 0, 9, 6, puzzle0_clue_20d },
    { 21, 8, 9, 6, puzzle0_clue_21d },
    { 22, 14, 9, 6, puzzle0_clue_22d },
    { 28, 10, 12, 3, puzzle0_clue_28d },
    { 29, 12, 12, 3, puzzle0_clue_29d },
};

// Grid template: # = black cell, A-Z = solution letters
static const char puzzle0_grid_template[GRID_HEIGHT][GRID_WIDTH + 1] = {
    "ARTIFICIAL#CHAT",
    "S#A#I#L#N###A#I",
    "IMPORTANT#UNLIT",
    "M#####U#I#N#L#H",
    "OAP#WIDTH#PAUSE",
    "V#R#H#E#E#O#C#S",
    "#MODE##GRAPHIC#",
    "##N#R#B#O#U#N##",
    "#GAMEBOY##LEAN#",
    "P#T#F#O#E#A#T#R",
    "AMARO#KHMER#ERA",
    "S#L#R#S#E#####N",
    "SPICE#HOTSTREAK",
    "E#S###O#I#I#S#L",
    "DATE#APOCALYPSE",
};

// Puzzle 0 definition
static Puzzle puzzle0 = {
    .title = "March Cryptic",
    .across_count = 18,
    .down_count = 16,
    .across_clues = puzzle0_across_clues,
    .down_clues = puzzle0_down_clues,
};
// Convert grid template to puzzle format
static void init_grid_from_template(Cell grid[GRID_HEIGHT][GRID_WIDTH],
                                    const char template[GRID_HEIGHT][GRID_WIDTH + 1]) {
    uint8_t clue_num = 1;

    for (uint8_t y = 0; y < GRID_HEIGHT; y++) {
        for (uint8_t x = 0; x < GRID_WIDTH; x++) {
            char c = template[y][x];
            Cell* cell = &grid[y][x];

            cell->player_input = CELL_EMPTY;
            cell->flags = 0;

            if (c == '#') {
                cell->solution = CELL_BLACK;
                cell->clue_num = 0;
            } else if (c == '.') {
                cell->solution = CELL_EMPTY;  // Unknown solution
                cell->clue_num = 0;
            } else if (c >= 'A' && c <= 'Z') {
                cell->solution = c;
                cell->clue_num = 0;

                // Check if this is start of a word (for clue numbering)
                uint8_t is_across_start = (x == 0 || grid[y][x-1].solution == CELL_BLACK) &&
                                          (x + 1 < GRID_WIDTH && template[y][x+1] != '#');
                uint8_t is_down_start = (y == 0 || grid[y-1][x].solution == CELL_BLACK) &&
                                        (y + 1 < GRID_HEIGHT && template[y+1][x] != '#');

                if (is_across_start) cell->flags |= FLAG_ACROSS_START;
                if (is_down_start) cell->flags |= FLAG_DOWN_START;

                if (is_across_start || is_down_start) {
                    cell->clue_num = clue_num++;
                }
            }
        }
    }
}

// Sample puzzle data
static Puzzle sample_puzzle = {
    .title = "Sample Puzzle",
    .across_count = 3,
    .down_count = 3,
    .across_clues = sample_across_clues,
    .down_clues = sample_down_clues,
};

const Puzzle* puzzles_get(uint8_t index) {
    if (index == 0) {
        // Initialize grid from template on first access
        static uint8_t initialized = 0;
        if (!initialized) {
            init_grid_from_template(puzzle0.grid, puzzle0_grid_template);
            initialized = 1;
        }
        return &puzzle0;
    }
    return NULL;
}

const char* puzzles_get_title(uint8_t index) {
    if (index == 0) {
        return puzzle0.title;
    }
    return "Unknown";
}

void puzzles_init_player_grid(Puzzle* dest, uint8_t puzzle_index) {
    const Puzzle* src = puzzles_get(puzzle_index);
    if (src == NULL) return;

    // Copy puzzle structure
    memcpy(dest, src, sizeof(Puzzle));

    // Clear player inputs
    for (uint8_t y = 0; y < GRID_HEIGHT; y++) {
        for (uint8_t x = 0; x < GRID_WIDTH; x++) {
            if (dest->grid[y][x].solution != CELL_BLACK) {
                dest->grid[y][x].player_input = CELL_EMPTY;
            }
        }
    }
}
